ALTER TABLE public.users ADD COLUMN IF NOT EXISTS overtidsprosent INTEGER NOT NULL DEFAULT 40;
ALTER TABLE public.timeregistrering ADD COLUMN IF NOT EXISTS overtidsprosent INTEGER NOT NULL DEFAULT 40;
